version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "13:00"
  open-pull-requests-limit: 10
  reviewers:
  - Ericky14
  assignees:
  - Ericky14
  ignore:
  - dependency-name: urijs
    versions:
    - 1.19.5
  - dependency-name: elliptic
    versions:
    - 6.5.3
  - dependency-name: handlebars
    versions:
    - 4.7.6
