image: node:8.11.4
options:
  max-time: 20
pipelines:
  custom:
    standard:
        - step: &install
            name: Get Dependencies
            caches:
            - node
            script:
            - yarn install
            artifacts:
            - node_modules/**
            - public/**
        - parallel: &tests
            - step:
                name: Lint
                script:
                - npm run lint
            - step:
                name: Unit Test
                script:
                - npm run test
  default:
    - step: *install
    - parallel: *tests
  branches:
    master:
      - step: *install
      - parallel: *tests
